# Criando Array

In [1]:
import numpy as np

## Array de zero 

In [4]:
print(np.zeros((3,6)))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Aleatório de 0 a 1

In [5]:
print(np.random.random((2,4)))

[[0.69734906 0.91807412 0.35666664 0.34891421]
 [0.13154646 0.2735392  0.72716023 0.39209247]]


## Sequencia de numeros

In [7]:
# De 0 ate 9 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# vamos supor que queremos que começe apatir de 50
np.arange(50,60)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [12]:
# Vamos supor que queremos seja sequencia de multiplo de 3 do intervelo de 0 a 100
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## Criando de tamanho n

In [16]:
linha1 = np.arange(10)
linha2 = np.arange(10,20)

matrix = np.array([linha1, linha2])

print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [6]:
import numpy as np
matriz43 = np.arange(12).reshape(4,3)
print(matriz43)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [43]:
z = np.arange(1,10)
tensor = np.array([matrix, matrix])

print(tensor)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]]


# Redimensionando 

In [18]:
linha1 = np.arange(10)
linha2 = np.arange(10,20)

matrix = np.array([linha1, linha2])

print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


## Reshape

In [19]:
# Vamos dimensionar para que seja uma matrix 4 por 5
print(matrix.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Flatten

Seria deixar os elementos em fila

In [21]:
print(matrix.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Fazendo operação com tamanho diferentes

In [17]:
import numpy as np

matriz43 = np.arange(12).reshape(4,3)
print(matriz43)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
matriz13 = np.arange(3)
matriz41 = np.arange(4).reshape((4,1))
print(matriz13)
print(matriz41)

[0 1 2]
[[0]
 [1]
 [2]
 [3]]


In [29]:
print(matriz43.shape, matriz13.shape,  matriz41.shape)

(4, 3) (3,) (4, 1)


In [30]:
print(matriz43 + matriz13)
print(matriz43 + matriz41)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [21]:
print(matriz43 * matriz13)

[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]
 [ 0 10 22]]


In [22]:
print(matriz13* matriz43)

[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]
 [ 0 10 22]]


# Tamanho da variável  (pensar um nome melhor)

## Tamanho padrão 

O elemento do bit, inicial começa 64bit por padrão 

In [23]:
t =  np.arange(10)
print(t.dtype)

int64


## Alterando o tamanho

In [26]:
t = t.astype(np.int8)
print(t.dtype)

int8


## Inciando com um tamanho



In [27]:
float32_array = np.array([1.32, 5.78, 175.55], dtype=np.float32)
float32_array.dtype

dtype('float32')

# Acessando o Elemento 

In [30]:
linha1 = np.arange(10)
linha2 = np.arange(10,20)

matrix = np.array([linha1, linha2])

print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [31]:
print(matrix[1,2])

12


In [44]:
z = np.arange(1,10)
tensor = np.array([matrix,matrix])

print(tensor)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]]


In [45]:
print(tensor[1][0,3])

3


## intervalo de elemento 

In [46]:
print(matrix[:,1])

[ 1 11]


In [47]:
print(matrix[1,:])

[10 11 12 13 14 15 16 17 18 19]


In [54]:
print(matrix[0,1:10:3])

[1 4 7]


## Filtro 

In [55]:
mask = matrix[:,1] > 1
print(matrix[mask])

[[10 11 12 13 14 15 16 17 18 19]]


vamos utirizar **where** que retorna a posição do indice 

In [56]:
indice = np.where(matrix[:,1] > 1)

print(indice)

print(matrix[indice])

(array([1]),)
[[10 11 12 13 14 15 16 17 18 19]]


# Concatenação

## Linha

In [71]:
matrix = np.array([[1,1], [2,2]])

print(matrix.shape)

(2, 2)


In [79]:
linha = np.array([[3,3])
linha.shape

(1, 2)

In [80]:
cont = np.concatenate((matrix,linha)) 
print(cont)

[[1 1]
 [2 2]
 [3 3]]


## Coluna

In [82]:
matrix = np.array([[1,1], [2,2]])
coluna = np.array([[3],[3]])

print(matrix.shape, coluna.shape)

(2, 2) (2, 1)


In [84]:
cont = np.concatenate((matrix,coluna), axis=1) 

print(cont)

[[1 1 3]
 [2 2 3]]


# Deletando 

In [86]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
deletando_linha = np.delete(matrix, 1, axis=0)

print(deletando_linha)

[[1 2 3]
 [7 8 9]]


In [89]:
deletando_coluna = np.delete(matrix, 1, axis=1)

print(deletando_coluna)

[[1 3]
 [4 6]
 [7 9]]


In [92]:
# Usando where como auxiliar

mask = np.where(matrix[:,2] < 5)

deletando = np.delete(matrix, mask, axis=1)


print(deletando)

[[2 3]
 [5 6]
 [8 9]]


# Transformando matriz (pensar um nome melhor)

## Flip

In [38]:
array = np.array([[1.1, 1.2, 1.3],
[2.1, 2.2, 2.3],
[3.1, 3.2, 3.3],
[4.1, 4.2, 4.3]])
np.flip(array)

array([[4.3, 4.2, 4.1],
       [3.3, 3.2, 3.1],
       [2.3, 2.2, 2.1],
       [1.3, 1.2, 1.1]])

In [43]:
array = np.arange(12)

np.flip(array)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Transposta 

In [39]:
array = np.array([[1.1, 1.2, 1.3],
[2.1, 2.2, 2.3],
[3.1, 3.2, 3.3],
[4.1, 4.2, 4.3]])
np.transpose(array)

array([[1.1, 2.1, 3.1, 4.1],
       [1.2, 2.2, 3.2, 4.2],
       [1.3, 2.3, 3.3, 4.3]])

#  Eficiência 

## Vectorize

Em NumPy, a vetorização refere-se à prática de substituir loops explícitos em Python por operações vetorizadas em arrays NumPy. A vetorização é uma técnica eficiente que explora a capacidade do NumPy de realizar operações em arrays inteiros, evitando loops e, assim, melhorando significativamente o desempenho do código.

A vetorização é possível devido à capacidade do NumPy de realizar operações em arrays inteiros de forma eficiente, conhecida como operações vetorizadas. Essas operações permitem que você execute cálculos em arrays inteiros sem a necessidade de escrever explicitamente loops em Python.

### Exemplo:


In [33]:
nomes = np.array(["ricardo", "leticia", "fatima", "roberto"])

vectorize_upper = np.vectorize(str.upper)

# Aplicando 
upper_nomes = vectorize_upper(nomes)

print(upper_nomes)

['RICARDO' 'LETICIA' 'FATIMA' 'ROBERTO']


#  Arquivo 

Acredito que não é comum temos arquivo em numpy mas

## leitura

Encontra um arquvivo bacana para colocar como exemplo, repare que a extensão do arquivo np

In [34]:
with open("file.np", "rb") as f:
    array = np.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'file.np'

## Salvar

In [ ]:
with open("file.npy", "wb") as f:
    np.save(f, array)

# Ajuda

Usamos help para obtemos informação da função e do metódo

~~~python
#para metodo 
help(np.ndarray.metodo)

#para função 
help(np.função)
~~~

Preciso verifica se para metódo realmente precisamos colocar `ndarray`

In [37]:
help(np.ndarray.flatten)

Help on method_descriptor:

flatten(...)
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.
    
    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.
    
    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.
    
    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4])



In [35]:
help(np.ndarray.astype)

Help on method_descriptor:

astype(...)
    a.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
    
    Copy of the array, cast to a specified type.
    
    Parameters
    ----------
    dtype : str or dtype
        Typecode or data-type to which the array is cast.
    order : {'C', 'F', 'A', 'K'}, optional
        Controls the memory layout order of the result.
        'C' means C order, 'F' means Fortran order, 'A'
        means 'F' order if all the arrays are Fortran contiguous,
        'C' order otherwise, and 'K' means as close to the
        order the array elements appear in memory as possible.
        Default is 'K'.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur. Defaults to 'unsafe'
        for backwards compatibility.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means only cas

In [36]:
help(np.unique)

Help on function unique in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
    Find the unique elements of an array.
    
    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:
    
    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array
    
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
        axis, if pro

# Fatiando a dimensão 

Vamos supor que nos temo esse dados

In [46]:
rgb = np.array([[[255, 0, 0], [255, 255, 0], [255, 255, 255]],
[[255, 0, 255], [0, 255, 0], [0, 255, 255]],
[[0, 0, 0], [0, 255, 255], [0, 0, 255]]])

print(rgb)

[[[255   0   0]
  [255 255   0]
  [255 255 255]]

 [[255   0 255]
  [  0 255   0]
  [  0 255 255]]

 [[  0   0   0]
  [  0 255 255]
  [  0   0 255]]]


queremos separa dessa forma

In [47]:
red_array = rgb[:, :, 0]
green_array = rgb[:, :, 1]
blue_array = rgb[:, :, 2]
red_array

array([[255, 255, 255],
       [255,   0,   0],
       [  0,   0,   0]])

podemos usar split para facilitar

In [48]:
red_array, green_array, blue_array = np.split(rgb, 3, axis=2)
red_array

array([[[255],
        [255],
        [255]],

       [[255],
        [  0],
        [  0]],

       [[  0],
        [  0],
        [  0]]])

Bom  na verdade ainda não esta igual, pois temos uma dimensão a mais

In [49]:
red_array.shape

(3, 3, 1)

vamos resolver retirando 

In [50]:
red_array_2D = red_array.reshape((3, 3))
red_array_2D

array([[255, 255, 255],
       [255,   0,   0],
       [  0,   0,   0]])

## Desfatiando 

In [51]:
rgb = np.stack([red_array, green_array, blue_array], axis=2)